services:
  backend:
    build:
      context: ./POS-Backend
      dockerfile: Dockerfile
    container_name: pos_backend
    ports:
      - "7089:7089"
    environment:
      - DOTNET_ENVIRONMENT=Development

  frontend:
    build:
      context: ./POS-Frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_DOMAIN=http://localhost:7089
    container_name: pos_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
